# Generated by Django 6.0.1 on 2026-03-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_timestamp', models.CharField(max_length=50)),
                ('request_id', models.CharField(max_length=50)),
                ('action_taken', models.CharField(max_length=50)),
                ('admin_username', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=150)),
                ('quantity', models.FloatField()),
                ('request_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50, unique=True)),
                ('material_name', models.CharField(max_length=150)),
                ('unit', models.CharField(default='MT', max_length=20)),
                ('current_balance', models.FloatField(default=0.0)),
                ('min_threshold', models.FloatField(default=0.0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('raw_material', models.CharField(max_length=150)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='MT', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('request_date', models.CharField(max_length=50)),
                ('request_time', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approval_time', models.CharField(blank=True, max_length=50)),
                ('lab_id', models.CharField(blank=True, max_length=50)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.CharField(blank=True, max_length=50)),
                ('request_type', models.CharField(default='BORROW', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker_id', models.CharField(blank=True, max_length=50)),
                ('sample_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('batch_id', models.CharField(blank=True, max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('moisture', models.CharField(blank=True, max_length=50)),
                ('purity', models.CharField(blank=True, max_length=50)),
                ('analyst', models.CharField(max_length=100)),
                ('sample_date', models.CharField(max_length=50)),
                ('sample_time', models.CharField(max_length=50)),
                ('lab', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('anomaly_flag', models.CharField(default='NO', max_length=20)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('review_status', models.CharField(blank=True, max_length=50)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TankerArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker_id', models.CharField(max_length=50, unique=True)),
                ('tanker_no', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=150)),
                ('quantity', models.FloatField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('arrival_date', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('sampling_date', models.CharField(blank=True, max_length=50)),
                ('sampling_time', models.CharField(blank=True, max_length=50)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=50)),
                ('lab', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TankerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker_no', models.CharField(max_length=50)),
                ('movement_type', models.CharField(max_length=50)),
                ('material_or_product', models.CharField(max_length=150)),
                ('quantity', models.FloatField()),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('source_destination', models.CharField(blank=True, max_length=200)),
                ('recorded_by', models.CharField(max_length=100)),
                ('recorded_at', models.CharField(max_length=50)),
                ('lab', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_id', models.CharField(max_length=50, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('qty_added', models.FloatField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventorymaster')),
            ],
        ),
    ]
