# Generated by Django 6.0.1 on 2026-03-22 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('ANOMALY', 'Anomaly'), ('SYSTEM', 'System')], max_length=20)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], default='INFO', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lab', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'lab'], name='api_systema_is_acti_a1c398_idx'), models.Index(fields=['is_active', 'alert_type'], name='api_systema_is_acti_879945_idx')],
            },
        ),
    ]
