# Generated by Django 6.0.1 on 2026-03-22 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loginauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('lab', models.CharField(max_length=50)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('calibrated_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['next_due_date'],
                'indexes': [models.Index(fields=['lab', 'status'], name='api_instrum_lab_fd48dc_idx'), models.Index(fields=['next_due_date'], name='api_instrum_next_du_9f4fbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=50)),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('pending_tasks', models.TextField(blank=True)),
                ('equipment_status', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handed_over_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('handed_over_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lab', '-shift_date'], name='api_shiftha_lab_e8b929_idx')],
            },
        ),
    ]
