# Generated by Django 5.0.4 on 2026-03-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_instrumentcalibration_shifthandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='labdata',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tankerarrival',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tankerhistory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='material_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='material_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='raw_material',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='request_date',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryrequest',
            name='request_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='labdata',
            name='anomaly_flag',
            field=models.CharField(db_index=True, default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='labdata',
            name='product',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='labdata',
            name='sample_date',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='labdata',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='labdata',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='labdata',
            name='tanker_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tankerarrival',
            name='arrival_date',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tankerarrival',
            name='material',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tankerarrival',
            name='tanker_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tankerarrival',
            name='tanker_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tankerhistory',
            name='date',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tankerhistory',
            name='material_or_product',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tankerhistory',
            name='movement_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tankerhistory',
            name='tanker_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
