# api/product_schemas.py

# Definitions of product schemas mapping to their specific Excel sheets and required columns.
# type: 'text' | 'number' | 'date' | 'time'

PRODUCT_SCHEMAS = {
    "sa_iii": {
        "id": "sa_iii",
        "name": "SA III",
        "sheet_name": "SA III",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "pct_h2so4", "label": "% H2SO4 (Product)", "type": "number", "required": True},
            {"key": "turbidity_product", "label": "TURBIDITY (Product)", "type": "number", "required": True},
            {"key": "product_oleum", "label": "Product Oleum", "type": "number", "required": False},
            {"key": "supply_oleum", "label": "Supply Oleum", "type": "number", "required": False},
            {"key": "fe_ppm", "label": "Fe(ppm)", "type": "number", "required": True},
            {"key": "free_so2", "label": "FREE SO2", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "sa_iv": {
        "id": "sa_iv",
        "name": "SA IV",
        "sheet_name": "SA IV",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "pct_h2so4_product", "label": "% H2SO4 (Product)", "type": "number", "required": True},
            {"key": "turbidity_product", "label": "TURBIDITY (Product)", "type": "number", "required": True},
            {"key": "product_oleum", "label": "Product Oleum", "type": "number", "required": False},
            {"key": "supply_oleum", "label": "Supply Oleum", "type": "number", "required": False},
            {"key": "pct_h2so4_sell", "label": "% H2SO4 (Sell Supply)", "type": "number", "required": False},
            {"key": "turbidity_sell", "label": "TURBIDITY (Sell Supply)", "type": "number", "required": False},
            {"key": "fe_ppm", "label": "Fe(ppm)", "type": "number", "required": True},
            {"key": "free_so2", "label": "FREE SO2", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
            {"key": "extra", "label": "EXTRA", "type": "text", "required": False},
            {"key": "remark", "label": "REMARK", "type": "text", "required": False},
        ]
    },
    "hno3": {
        "id": "hno3",
        "name": "HNO3",
        "sheet_name": "HNO3",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "hno3_a", "label": "HNO3_A", "type": "number", "required": True},
            {"key": "hno3_b", "label": "HNO3_B", "type": "number", "required": True},
            {"key": "remarks", "label": "Remarks", "type": "text", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
            {"key": "final_remark", "label": "REMARK", "type": "text", "required": False},
        ]
    },
    "caustic": {
        "id": "caustic",
        "name": "Caustic",
        "sheet_name": "Caustic",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "time", "label": "Time", "type": "time", "required": True},
            {"key": "plant", "label": "Plant", "type": "text", "required": True},
            {"key": "tanker_no", "label": "Tanker No", "type": "text", "required": True},
            {"key": "front_top", "label": "Front Top", "type": "number", "required": False},
            {"key": "back_top", "label": "Back Top", "type": "number", "required": False},
            {"key": "bottom", "label": "Bottom", "type": "number", "required": False},
            {"key": "party", "label": "Party", "type": "text", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
            {"key": "difference", "label": "Difference", "type": "number", "required": False},
        ]
    },
    "hcl": {
        "id": "hcl",
        "name": "HCl",
        "sheet_name": "HCl",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "time", "label": "Time", "type": "time", "required": True},
            {"key": "supplier", "label": "Supplier", "type": "text", "required": True},
            {"key": "tanker_no", "label": "Tanker No", "type": "text", "required": True},
            {"key": "result", "label": "Result", "type": "number", "required": True},
            {"key": "party", "label": "Party", "type": "text", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "daily_s": {
        "id": "daily_s",
        "name": "Daily S",
        "sheet_name": "Daily S",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of sampling", "type": "date", "required": True},
            {"key": "sampling_point", "label": "sampling point", "type": "text", "required": True},
            {"key": "no_trucks", "label": "No Trucks", "type": "number", "required": True},
            {"key": "ash", "label": "Ash", "type": "number", "required": True},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "plant_s": {
        "id": "plant_s",
        "name": "Plant S",
        "sheet_name": "Plant S",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of sampling", "type": "date", "required": True},
            {"key": "sampling_point", "label": "Sampling Point", "type": "text", "required": True},
            {"key": "ash", "label": "Ash", "type": "number", "required": True},
            {"key": "acidity", "label": "Acidity", "type": "number", "required": True},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "tanker_sulphur": {
        "id": "tanker_sulphur",
        "name": "TANKER SULPHUR",
        "sheet_name": "TANKER SULPHUR",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of sampling", "type": "date", "required": True},
            {"key": "tanker_no", "label": "TANKER NUMBER", "type": "text", "required": True},
            {"key": "pct_moisture", "label": "% Moisture", "type": "number", "required": True},
            {"key": "pct_organic_matter", "label": "% Organic Matter", "type": "number", "required": True},
            {"key": "pct_ash", "label": "% Ash", "type": "number", "required": True},
            {"key": "pct_purity", "label": "% Purity", "type": "number", "required": True},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "acidity", "label": "Acidity", "type": "number", "required": False},
            {"key": "checked_by", "label": "Check / Checked By", "type": "text", "required": True},
        ]
    },
    "composite_s": {
        "id": "composite_s",
        "name": "Composite S",
        "sheet_name": "Composite S",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of sampling", "type": "date", "required": True},
            {"key": "sampling_point", "label": "Sampling point", "type": "text", "required": True},
            {"key": "no_trucks", "label": "No Trucks", "type": "number", "required": True},
            {"key": "moisture", "label": "Moisture", "type": "number", "required": True},
            {"key": "organic_matter", "label": "Organic Matter", "type": "number", "required": True},
            {"key": "ash", "label": "Ash", "type": "number", "required": True},
            {"key": "screen", "label": "Screen", "type": "text", "required": False},  # May be split, keeping generic
            {"key": "purity", "label": "Purity", "type": "number", "required": True},
            {"key": "crushing_strength", "label": "Crushing strength", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "misc": {
        "id": "misc",
        "name": "MISC",
        "sheet_name": "MISC",
        "fields": [
            {"key": "turbidity", "label": "TURBIDITY", "type": "number", "required": False},
            {"key": "sp_gravity", "label": "Sp.Gravity", "type": "number", "required": False},
            {"key": "free_so2", "label": "FREE SO2 ppm", "type": "number", "required": False},
            {"key": "roi_ppm", "label": "ROI ppm", "type": "number", "required": False},
            {"key": "fe_ppm", "label": "Fe ppm", "type": "number", "required": False},
            {"key": "pb_ppm", "label": "Pb ppm", "type": "number", "required": False},
            {"key": "chloride_ppm", "label": "Chloride ppm", "type": "number", "required": False},
            {"key": "arsenic_ppm", "label": "Arsenic ppm", "type": "number", "required": False},
            {"key": "pct_purity_sulphur", "label": "% PURITY OF SULPHUR", "type": "number", "required": False},
            {"key": "pct_ash", "label": "% ASH", "type": "number", "required": False},
            {"key": "pct_organic_matter", "label": "% ORGANIC MATTER", "type": "number", "required": False},
            {"key": "pct_moisture", "label": "% MOISTURE", "type": "number", "required": False},
            {"key": "bulk_density", "label": "BULK DENSITY GM/CC", "type": "number", "required": False},
            {"key": "crushing_strength", "label": "CRUSHING STRENGTH Kg/Cm2", "type": "number", "required": False},
            {"key": "pct_screen_plus_300", "label": "% SCREEN +300", "type": "number", "required": False},
            {"key": "pct_screen_minus_300", "label": "% SCREEN -300", "type": "number", "required": False},
            {"key": "analyst", "label": "ANALYST", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "nylon_6": {
        "id": "nylon_6",
        "name": "Nylon-6",
        "sheet_name": "NY-1CONT.",
        "fields": [
            {"key": "dater", "label": "Date", "type": "date", "required": True},
            {"key": "batch_no", "label": "Batch No", "type": "text", "required": True},
            {"key": "grade", "label": "Grade (eg. E-24, E-28)", "type": "text", "required": True},
            {"key": "rv", "label": "RV", "type": "number", "required": True},
            {"key": "moisture", "label": "H2O % (Moisture)", "type": "number", "required": True},
            {"key": "we", "label": "WE %", "type": "number", "required": False},
            {"key": "nh2", "label": "NH2", "type": "number", "required": False},
            {"key": "cooh", "label": "COOH", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
        ]
    },
    "urea": {
        "id": "urea",
        "name": "Urea",
        "sheet_name": "Urea",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "time", "label": "Time", "type": "time", "required": True},
            {"key": "batch_no", "label": "Batch No", "type": "text", "required": True},
            {"key": "sample_id", "label": "Sample ID", "type": "text", "required": False},
            {"key": "pct_nitrogen", "label": "% Nitrogen (N)", "type": "number", "required": True},
            {"key": "pct_biuret", "label": "% Biuret", "type": "number", "required": True},
            {"key": "moisture", "label": "% Moisture", "type": "number", "required": True},
            {"key": "purity", "label": "% Purity", "type": "number", "required": True},
            {"key": "particle_size", "label": "Particle Size (mm)", "type": "number", "required": False},
            {"key": "crushing_strength", "label": "Crushing Strength (Kg)", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "dap": {
        "id": "dap",
        "name": "DAP",
        "sheet_name": "DAP",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "time", "label": "Time", "type": "time", "required": True},
            {"key": "batch_no", "label": "Batch No", "type": "text", "required": True},
            {"key": "sample_id", "label": "Sample ID", "type": "text", "required": False},
            {"key": "pct_nitrogen", "label": "% Nitrogen (N)", "type": "number", "required": True},
            {"key": "pct_p2o5", "label": "% P2O5", "type": "number", "required": True},
            {"key": "moisture", "label": "% Moisture", "type": "number", "required": True},
            {"key": "purity", "label": "% Purity", "type": "number", "required": True},
            {"key": "particle_size", "label": "Particle Size (mm)", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "npk": {
        "id": "npk",
        "name": "NPK",
        "sheet_name": "NPK",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "time", "label": "Time", "type": "time", "required": True},
            {"key": "batch_no", "label": "Batch No", "type": "text", "required": True},
            {"key": "sample_id", "label": "Sample ID", "type": "text", "required": False},
            {"key": "grade", "label": "Grade (eg. 10:26:26)", "type": "text", "required": True},
            {"key": "pct_nitrogen", "label": "% Nitrogen (N)", "type": "number", "required": True},
            {"key": "pct_p2o5", "label": "% P2O5", "type": "number", "required": True},
            {"key": "pct_k2o", "label": "% K2O", "type": "number", "required": True},
            {"key": "moisture", "label": "% Moisture", "type": "number", "required": True},
            {"key": "purity", "label": "% Purity", "type": "number", "required": True},
            {"key": "particle_size", "label": "Particle Size (mm)", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
    "ammonia": {
        "id": "ammonia",
        "name": "Ammonia",
        "sheet_name": "Ammonia",
        "fields": [
            {"key": "dater", "label": "Date of Reporting", "type": "date", "required": True},
            {"key": "datep", "label": "Date of Sampling", "type": "date", "required": True},
            {"key": "time", "label": "Time", "type": "time", "required": True},
            {"key": "batch_no", "label": "Batch No", "type": "text", "required": True},
            {"key": "sample_id", "label": "Sample ID", "type": "text", "required": False},
            {"key": "purity", "label": "% Purity (NH3)", "type": "number", "required": True},
            {"key": "moisture", "label": "% Moisture", "type": "number", "required": True},
            {"key": "oil_content", "label": "Oil Content (ppm)", "type": "number", "required": False},
            {"key": "analyst", "label": "Analyst", "type": "text", "required": True},
            {"key": "checked_by", "label": "Checked By", "type": "text", "required": True},
        ]
    },
}

